name: Publish Version Update

on:
  push:
    branches:
      - sesl/master
    paths:
      - 'build.gradle'
  workflow_dispatch:
jobs:
  check-and-publish:
    env:
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Detect lib version change
        id: lib_version_check
        run: |
          # Get the previous commit hash on main
          PREV_COMMIT=$(git rev-parse HEAD^)
          OLD_VERSION=$(git show "$PREV_COMMIT":build.gradle | grep 'mdcLibraryVersion\s*=' | sed -E "s/.*mdcLibraryVersion\s*=\s*['\"]([^'\"]+)['\"].*/\1/")
          NEW_VERSION=$(grep 'mdcLibraryVersion\s*=' build.gradle | sed -E "s/.*mdcLibraryVersion\s*=\s*['\"]([^'\"]+)['\"].*/\1/")
        
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
          
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
          else
          echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish module update
        if: steps.lib_version_check.outputs.changed == 'true'
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository

      - name: Generate and publish Dokka docs
        if: steps.lib_version_check.outputs.changed == 'true'
        run: |
          ./gradlew dokkaHtml

      - name: Publish to GitHub Pages
        if: steps.lib_version_check.outputs.changed == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: lib/build/dokka/html
